export {
  CodeChunkEmbeddingService,
  createOpenAICodeChunkEmbeddingServiceFromEnv,
  type CodeChunkEmbeddingOptions,
  type CodeChunkEmbeddingResult,
  type EmbeddedCodeChunk,
} from "./code-chunk-embedding-service.js";
export {
  Cl100kEmbeddingTokenCounter,
  EmbeddingGenerationError,
  EmbeddingGenerator,
  OpenAIEmbeddingProvider,
  createOpenAIEmbeddingGenerator,
  createOpenAIEmbeddingGeneratorFromEnv,
  defaultEmbeddingBatchSize,
  defaultEmbeddingDimensions,
  defaultEmbeddingModel,
  defaultEmbeddingRequestConcurrency,
  defaultMaxEmbeddingInputTokens,
  defaultMaxEmbeddingRequestTokens,
  defaultOpenAIMaxRetries,
  defaultOpenAIRequestTimeoutMs,
  maximumOpenAIEmbeddingInputsPerRequest,
  maximumOpenAIEmbeddingTokensPerRequest,
  type EmbeddingGenerationErrorCode,
  type EmbeddingGenerationOptions,
  type EmbeddingGenerationResult,
  type EmbeddingGenerationUsage,
  type EmbeddingGeneratorConfig,
  type EmbeddingInput,
  type EmbeddingProvider,
  type EmbeddingProviderRequest,
  type EmbeddingProviderRequestOptions,
  type EmbeddingProviderResponse,
  type EmbeddingTokenCounter,
  type GeneratedEmbedding,
  type OpenAIEmbeddingGeneratorConfig,
  type OpenAIEmbeddingProviderConfig,
} from "./embedding-generator.js";
export {
  EmbeddingTextFormatError,
  formatCodeChunkForEmbedding,
  type CodeChunkEmbeddingTextOptions,
} from "./embedding-text.js";
export {
  GoogleAnswerProvider,
  GoogleEmbeddingProvider,
  createGoogleEmbeddingGeneratorFromEnv,
  createGoogleRepositoryAnswerGeneratorFromEnv,
  defaultGoogleApiBaseUrl,
  defaultGoogleChatModel,
  defaultGoogleEmbeddingDimensions,
  defaultGoogleEmbeddingModel,
  defaultGoogleRequestTimeoutMs,
  type GoogleEmbeddingProviderConfig,
  type GoogleEmbeddingPurpose,
  type GoogleProviderConfig,
} from "./google-provider.js";
export {
  OllamaAnswerProvider,
  OllamaEmbeddingProvider,
  createOllamaEmbeddingGeneratorFromEnv,
  createOllamaRepositoryAnswerGeneratorFromEnv,
  defaultOllamaChatModel,
  defaultOllamaEmbeddingDimensions,
  defaultOllamaEmbeddingModel,
  defaultOllamaKeepAlive,
  defaultOllamaRequestTimeoutMs,
  defaultOllamaUrl,
  type OllamaProviderConfig,
} from "./ollama-provider.js";
export {
  AIProviderError,
  classifyAIProviderError,
  type AIProviderErrorCode,
  type AIProviderFailure,
  type AIProviderName,
} from "./provider-error.js";
export {
  createCodeChunkEmbeddingServiceFromEnv,
  createEmbeddingGeneratorFromEnv,
  createQuestionEmbeddingServiceFromEnv,
  createRepositoryAnswerGeneratorFromEnv,
  defaultAIProvider,
  resolveAIProvider,
} from "./provider-factory.js";
export {
  classifyRepositoryQuestion,
  extractExactSymbolName,
  repositoryQuestionCategories,
  type RepositoryQuestionCategory,
} from "./question-classifier.js";
export {
  QuestionEmbeddingService,
  createOpenAIQuestionEmbeddingServiceFromEnv,
  maximumRepositoryQuestionCharacters,
  type QuestionEmbedding,
} from "./question-embedding-service.js";
export {
  OpenAIAnswerProvider,
  RepositoryAnswerError,
  RepositoryAnswerGenerator,
  createOpenAIRepositoryAnswerGeneratorFromEnv,
  defaultAnswerMaxOutputTokens,
  defaultAnswerModel,
  defaultMaximumConversationHistoryCharacters,
  defaultMaximumRepositoryContextCharacters,
  type AnswerProvider,
  type AnswerProviderRequest,
  type AnswerProviderRequestOptions,
  type AnswerProviderResponse,
  type AnswerTokenUsage,
  type OpenAIAnswerProviderConfig,
  type RepositoryAnswerErrorCode,
  type RepositoryAnswerCitation,
  type RepositoryAnswerGeneratorConfig,
  type RepositoryAnswerRequest,
  type RepositoryAnswerResult,
  type RepositoryAnswerSource,
  type RepositoryConversationMessage,
} from "./repository-answer-generator.js";
